### ISSUE TITLE
Issue in http index task

### ISSUE THREAD

**Issue by brunowego** [johngeorgewright/grunt-http#24]
After run http:index I get this error:

```bash
Running "http:index" (http) task
Fatal error: 500 Error: connect ECONNREFUSED<br> &nbsp; &nbsp;at exports._errnoException (util.js:746:11)<br> &nbsp; &nbsp;at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
```

File `http.js`:
```js
module.exports = {
  index: {
    options: {
      url: 'http://<%= connect.fetch.options.hostname %>:<%= connect.fetch.options.port %>/'
    },
    dest: '.tmp/index.html'
  }
};
```

Any Idea about this issue? Thanks!

OSX 10.10

**Comment by johngeorgewright** [comment]
Looks like whatever you're trying to access is returning a 500 error.

**Comment by brunowego** [comment]
Yes, I think this is a bug with my app. Thanks!
